const starAPIMock =
[
  {
    climate: "arid",
    created: "2014-12-09T13:50:49.641000Z",
    diameter: "10465",
    edited: "2014-12-20T20:58:18.411000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/1/', 'https://swapi-trybe.herokuapp.com/api/films/3/', 'https://swapi-trybe.herokuapp.com/api/films/4/', 'https://swapi-trybe.herokuapp.com/api/films/5/', 'https://swapi-trybe.herokuapp.com/api/films/6/'],
    gravity: "1 standard",
    name: "Tatooine",
    orbital_period: "304",
    population: "200000",
    residents: ['https://swapi-trybe.herokuapp.com/api/people/1/', 'https://swapi-trybe.herokuapp.com/api/people/2/', 'https://swapi-trybe.herokuapp.com/api/people/4/', 'https://swapi-trybe.herokuapp.com/api/people/6/', 'https://swapi-trybe.herokuapp.com/api/people/7/', 'https://swapi-trybe.herokuapp.com/api/people/8/', 'https://swapi-trybe.herokuapp.com/api/people/9/', 'https://swapi-trybe.herokuapp.com/api/people/11/', 'https://swapi-trybe.herokuapp.com/api/people/43/', 'https://swapi-trybe.herokuapp.com/api/people/62/'],
    rotation_period: "23",
    surface_water: "1",
    terrain: "desert",
    url: "https://swapi-trybe.herokuapp.com/api/planets/1/",
  },
  {
    climate: "temperate",
    created: "2014-12-10T11:35:48.479000Z",
    diameter: "12500",
    edited: "2014-12-20T20:58:18.420000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/1/', 'https://swapi-trybe.herokuapp.com/api/films/6/'],
    gravity: "1 standard",
    name: "Alderaan",
    orbital_period: "364",
    population: "2000000000",
    residents: ['https://swapi-trybe.herokuapp.com/api/people/5/', 'https://swapi-trybe.herokuapp.com/api/people/68/', 'https://swapi-trybe.herokuapp.com/api/people/81/'],
    rotation_period: "24",
    surface_water: "40",
    terrain: "grasslands, mountains",
    url: "https://swapi-trybe.herokuapp.com/api/planets/2/",
  },
  {
    climate: "temperate, tropical",
    created: "2014-12-10T11:37:19.144000Z",
    diameter: "10200",
    edited: "2014-12-20T20:58:18.421000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/1/'],
    gravity: "1 standard",
    name: "Yavin IV",
    orbital_period: "4818",
    population: "1000",
    residents: [],
    rotation_period: "24",
    surface_water: "8",
    terrain: "jungle, rainforests",
    url: "https://swapi-trybe.herokuapp.com/api/planets/3/",
  },
  {
    climate: "frozen",
    created: "2014-12-10T11:39:13.934000Z",
    diameter: "7200",
    edited: "2014-12-20T20:58:18.423000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/2/'],
    gravity: "1.1 standard",
    name: "Hoth",
    orbital_period: "549",
    population: "unknown",
    residents: [],
    rotation_period: "23",
    surface_water: "100",
    terrain: "tundra, ice caves, mountain ranges",
    url: "https://swapi-trybe.herokuapp.com/api/planets/4/",
  },
  {
    climate: "murky",
    created: "2014-12-10T11:42:22.590000Z",
    diameter: "8900",
    edited: "2014-12-20T20:58:18.425000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/2/', 'https://swapi-trybe.herokuapp.com/api/films/3/', 'https://swapi-trybe.herokuapp.com/api/films/6/'],
    gravity: "N/A",
    name: "Dagobah",
    orbital_period: "341",
    population: "unknown",
    residents: [],
    rotation_period: "23",
    surface_water: "8",
    terrain: "swamp, jungles",
    url: "https://swapi-trybe.herokuapp.com/api/planets/5/",
  },
  {
    climate: "temperate",
    created: "2014-12-10T11:43:55.240000Z",
    diameter: "118000",
    edited: "2014-12-20T20:58:18.427000Z",
    films: ['https://swapi-trybe.herokuapp.com/api/films/2/'],
    gravity: "1.5 (surface), 1 standard (Cloud City)",
    name: "Bespin",
    orbital_period: "5110",
    population: "6000000",
    residents: ['https://swapi-trybe.herokuapp.com/api/people/26/'],
    rotation_period: "12",
    surface_water: "0",
    terrain: "gas giant",
    url: "https://swapi-trybe.herokuapp.com/api/planets/6/",
  }
]

export default starAPIMock;
